name: mind_flow
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.5

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  provider: ^6.1.5
  hugeicons: ^0.0.11
  get_it: ^8.0.3
  shared_preferences: ^2.3.3
  fl_chart: ^0.64.0
  dotenv: ^4.2.0
  iconsax: ^0.0.8
  easy_localization: ^3.0.7+1
  lottie: ^3.1.3
  sqflite: ^2.3.3+1
  path: ^1.9.0
  crypto: ^3.0.3
  firebase_core: ^3.15.2
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.0
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  pretty_dio_logger: ^1.4.0
  leak_tracker: ^10.0.4
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^16.1.0
  in_app_purchase: ^3.2.0
  in_app_purchase_android: ^0.3.6+1
  connectivity_plus: ^6.1.4
  permission_handler: ^11.3.1
  clarity_flutter: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/config/
    - assets/lotties/
    - assets/pictures/
    - assets/translations/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800

