name: mind_flow
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  dio: ^5.8.0+1
  flutter_dotenv: ^5.2.1
  provider: ^6.1.5
  hugeicons: ^0.0.11
  get_it: ^8.0.3
  shared_preferences: ^2.3.3
  glassmorphism: ^3.0.0
  fl_chart: ^0.64.0
  dotenv: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/config/
